name: 'Run Checkov'
description: 'Check policies against Terraform plan file'
inputs:
  tf-policy-repo-token: # id of input
    description: 'Token for TF policy repo'
    required: true
  file-path:
    description: 'Path to the tfplan file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check tfplan JSON file
      shell: bash
      run: |
        jsonfile=${{ inputs.file-path }}
        if [ ! -f $jsonfile ]; then
          echo "File does not exist."
          exit 1
        fi
        echo "tfplan.json exists."
        cat $jsonfile | jq '.' > out.json

    - name: Install Checkov
      shell: bash
      run: |
        pip3 install checkov
        # Check if Checkov is installed
        if [[ $(pip3 list | grep -i "checkov") =~ "checkov" ]]; then
          echo "Checkov is installed."
        else
          echo "Checkov is not installed. Installation failed."
          exit 1
        fi

    - name: Run Checkov tests
      shell: bash
      run: |
        checkov -f out.json --external-checks-git https://${{ inputs.tf-policy-repo-token }}@github.com/cypiksuresh/iac-terraform-policies.git//checkov --skip-check 'CKV_*'
