name: 'Run Checkov'
description: 'Check policies against Terraform plan file'
inputs:
  tf-policy-repo-token: # id of input
    description: 'Token for TF policy repo'
    required: true
  file-path:
    description: 'Path to the tfplan file'
    required: true
  working-directory: # Add input for working directory
    description: 'Working directory where the tfplan file is located'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check tfplan json file
      shell: bash
      run: |
        jsonfile=${{ inputs.file-path }}
        working_dir=${{ inputs.working-directory }}  # Get the working directory from input
        full_path="${working_dir}/${jsonfile}"  # Construct the full path to tfplan file

        if [ ! -f $full_path ]; then
          echo "file does not exist: $full_path"
          exit 1
        fi
        echo "tfplan.json exists at $full_path."
        cat $full_path | jq '.' > out.json

    - name: Install checkov
      run: |
        pip3 install checkov
        # check if checkov is installed
        if [[ $(pip3 list | grep -i "checkov") =~ "checkov" ]]; then
          echo "checkov is installed"
        else
          echo "checkov is not installed"
          exit 1
        fi
      shell: bash

    - name: Run test checkov
      shell: bash
      run: |
        checkov -f out.json --external-checks-git https://${{ inputs.tf-policy-repo-token }}@github.com/cypiksuresh/iac-terraform-policies.git//checkov --skip-check 'CKV_*'
