name: Slack Notifier

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  slack-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on success
        if: success()
        uses: cypiksuresh/shared-workflows/.github/actions/automation-slack-notifier@master
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_message: '🎉 The workflow ran successfully!'

      - name: Notify on failure
        if: failure()
        uses: cypiksuresh/shared-workflows/.github/actions/automation-slack-notifier@master
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_message: '😞 The workflow encountered an error.'
