jobs:
  readme-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Updating GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
          token: ${{ env.GH_TOKEN }}

      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'create readme'
        uses: '8398a7/action-slack@v3.16.2'
        with:
          actions_subcommand: 'readme'
          github_token: '${{ secrets.TOKEN }}'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN}}

      - name: 'pre-commit check errors'
        uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - name: 'pre-commit fix errors'
        uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - name: 'push readme'
        uses: '8398a7/action-slack@v3.16.2'
        with:
          actions_subcommand: 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN}}

      - name: 'Slack Notification'
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}  # Correct way to pass the status
          fields: repo,author
          author_name: '8398a7'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()  # Ensure it runs regardless of job success or failure
